### ISSUE TITLE
Video API youtube search not working

### ISSUE THREAD

**Issue by Toppari** [jengmicah/watchparty#1]
Video API response is empty for /ytsearch endpoint.

https://video-meta.herokuapp.com/ytsearch?query=test&page=1&limit=9

**Comment by jengmicah** [comment]
YouTube seems to have phased out its old query results, which may have removed the ability to use a pagination token like we've been doing previously with the `&page=1`. They appear to be returning a `key` and `nextPageToken` with their query results, so I believe that is how we should be paginating. I'll be sure to take a look. Thanks for bringing this up!

**Comment by jengmicah** [comment]
I've fixed the YouTube query results but there's still an issue with pagination. I'll create a separate issue for that.
