### ISSUE TITLE
Youtube search isn't working

### ISSUE THREAD

**Issue by maddie-wang** [jengmicah/watchparty#6]
problem: when I search up a video on https://streamparty.netlify.app/room/semi-eel the website doesn't return the search results

![image](https://user-images.githubusercontent.com/32725368/111515097-677ed280-8720-11eb-9b56-5b46202f4c46.png)

**Comment by jengmicah** [comment]
Fixed! There was a small issue with the YT html parsing. Thank you for bringing this up!
